Update and rename defaultBrowserHeadlessChromeStandardInstall.yml to defaultBrowserIsChromeHeadless.yml

diff --git a/.github/workflows/defaultBrowserIsChromeHeadless.yml b/.github/workflows/defaultBrowserIsChromeHeadless.yml
--- a/.github/workflows/defaultBrowserIsChromeHeadless.yml
+++ b/.github/workflows/defaultBrowserIsChromeHeadless.yml
@@ -1,6 +1,6 @@
 # This is a basic workflow to help you get started with Actions
   
-name: Default Browser Headless Chrome Standard Install
+name: Default Browser is Chrome Headless 
 
 # Controls when the workflow will run
 on:
@@ -16,11 +16,19 @@ jobs:
     steps:
       - name: Install Chrome
         uses: browser-actions/setup-chrome@v1
+        # Manual install
+        # run: |
+        #   wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
+        #   echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
+        #   sudo apt-get update
+        #   sudo apt-get install -y google-chrome-stable curl
+
           
       - name: Create headless browser script
         run: |
           sudo tee /usr/local/bin/webBrowserHeadless > /dev/null << 'EOF'
           #!/bin/sh
+          # --dump-dom makes Chrome outputs HTML from built DOM, then quits
           google-chrome --headless=new \
           --disable-gpu \
           --no-sandbox \
@@ -30,11 +38,16 @@ jobs:
   
           sudo chmod +x /usr/local/bin/webBrowserHeadless
           
-      - name: Verify script creation
+      - name: Verify webBrowserHeadless script works as expected
         run: |
           ls -l /usr/local/bin/webBrowserHeadless
           cat /usr/local/bin/webBrowserHeadless
-          /usr/local/bin/webBrowserHeadless https://example.com
+          if grep -q "<title>Example Domain</title>" `webBrowserHeadless https://example.com` ; then
+            echo "✅ webBrowserHeadless executed successfully"
+          else
+            echo "❌ webBrowserHeadless failed"
+            exit 1
+          fi
           
       - name: Setup default browser
         run: |
@@ -42,17 +55,9 @@ jobs:
           sudo update-alternatives --set www-browser /usr/local/bin/webBrowserHeadless
           ls -l /etc/alternatives | grep browser
 
-      - name: Test opening some URL with webBrowserHeadless
+      - name: Test opening some URL with default browser (xdg-open)
         run: |
-          if webBrowserHeadless https://example.com; then
-            echo "✅ webBrowserHeadless executed successfully"
-          else
-            echo "❌ webBrowserHeadless failed"
-            exit 1
-          fi
-      - name: Test opening some URL
-        run: |
-          if xdg-open https://example.com; then
+          if grep -q "<title>Example Domain</title>" `xdg-open https://example.com` ; then
             echo "✅ xdg-open executed successfully"
           else
             echo "❌ xdg-open failed"
